// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpydwsvxbdktlowafnlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpweWR3c3Z4YmRrdGxvd2FmbmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDYwNzksImV4cCI6MjA1ODM4MjA3OX0.Uy3YwIlAnqbS2cvNRLecnPZmqsd_TczuKgdIb8SZz98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);